# Generated by Django 4.1.1 on 2022-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('trabaja', models.BooleanField()),
            ],
        ),
    ]
