# Generated by Django 4.1.1 on 2022-09-19 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas',
            name='email',
            field=models.CharField(default=datetime.date, max_length=50),
            preserve_default=False,
        ),
    ]
