# Generated by Django 4.1.1 on 2022-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_respuestas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='email',
            field=models.CharField(default='no ingreso correo', max_length=50),
        ),
    ]
